export const FETCH_POST_START = "FETCH_POST_START";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";

export const SHOW_SUCCESS = "SHOW_SUCCESS";
export const SHOW_FAIL = "SHOW_FAIL";